#!/bin/bash

# install dbus-x11 to work with cron

BAT_DIR=/sys/class/power_supply/
[[ -d "$BAT_DIR" ]] || exit
BAT_NAME=$(find "$BAT_DIR" -name "BAT*" -printf "%f")
[[ -n "$BAT_NAME" ]] || exit
BAT_PCT=$(cat "$BAT_DIR/$BAT_NAME/capacity")
BAT_STATUS=$(cat "$BAT_DIR/$BAT_NAME/status")

[[ $BAT_STATUS = "Charging" ]] && exit
if [[ $BAT_PCT -le 10 ]]; then
  notify-send -u critical 'Battery Low' "$BAT_PCT% remaining"
elif [[ $BAT_PCT -le 20 ]]; then
  notify-send -u normal 'Battery Low' "$BAT_PCT% remaining"
fi
